### PR TITLE
TASK-1175: Verify functionality with ref_paths

### PR DESCRIPTION
**Pull request by JamesJeffryes**
Didn't have to change the implementation at all. Just expanded the tests to verify and updated travis while I was at it

### CODE REVIEW

**Comment by JamesJeffryes** [comment]
@scanon @sychan Can you take a look? Mostly just updated test to confirm refpath functionality

**Comment by scanon** [comment]
James: This looks okay to merge, but shouldn't the whatever grabs the sequence in the annotate_genome do the reference chain lookup?

**Comment by JamesJeffryes** [comment]
I don't think I follow your comment but one thing I noticed is that we should update this app to use Genome File Util for parsing and saving the gff file as a new genome file.

**Comment by JamesJeffryes** [comment]
I don't have write access BTW so if you approve you will have to merge

**Pull request merged**
