### PR TITLE
Create separate app for AssemblySets and GenomeSets

### PR DESCRIPTION
**Pull request by landml**
@JamesJeffryes, @bio-boris 
I created a separate app for the Sets. It is identical except the widget output is 'no-display'. It was confusing the app with both genomes and genomeSets in the output cell. At least I think that is what the problem was.

### CODE REVIEW

**Comment by bio-boris** [comment]
@landml Should we change the valid_ws_types on the annotate_sets method to only accept 
   "valid_ws_types": ["KBaseSets.AssemblySet", "KBaseSearch.GenomeSet"]
And then change the annotate_contigs method to only accept
            "valid_ws_types": ["KBaseGenomeAnnotations.Assembly", "KBaseGenomes.Genome", ]
?

**Comment by bio-boris** [comment]
If this is just for testing, otherwise I can just merge and deploy this, let me know.

**Comment by landml** [comment]
Oh, I meant to change that. Then I remembered that in RAST I allowed users to add multiple genomes and genome sets all with the same app. I need to set "allow_multiple" to true. I'll do that now.

**Comment by bio-boris** [comment]
@landml Looks good to me, I can go ahead and merge and deploy now if you'd like.

**Comment by landml** [comment]
I can deploy if you will do the merge for me. Thank you.

**Pull request merged**
